# This file intentionally left blank
SPLIT_KEYBOARD = yes
COMBO_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = yes

BOOTMAGIC_ENABLE = no
LEADER_ENABLE = no
CONSOLE_ENABLE = no

